# Secrets pour la connexion à Supabase
    supabase_url = "https://lbqqpkscbwrnofwmwlih.supabase.co"
    supabase_key =
     "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxicXFwa3NjYndybm9md213bGloIiwicm9sZSI
     6ImFub24iLCJpYXQiOjE3NTQ5NTQxOTksImV4cCI6MjA3MDUzMDE5OX0.90qiRRhkgOu-4bMJhXVQCwFJs0ljfN8l88Xq8oHr044"
